# Generated by Django 5.2.3 on 2025-06-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20250624_2029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='URL изображения товара', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='wb_url',
            field=models.URLField(blank=True, help_text='Ссылка на товар на Wildberries', null=True),
        ),
    ]
